---
- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install PHP and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - php5
        - php5-cli
        - php5-curl
        - php5-fpm

    - name: Install Nginx and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - nginx

    - name: Put "vagrant" user in www-data group
      user:
        name: "vagrant"
        groups: "www-data"
        append: yes

    - name: Creates development directory
      file: path=/var/www state=directory owner=www-data group=www-data mode=0775

    - name: Creates development directory
      file: path=/vagrant/htdocs state=directory owner=www-data group=www-data mode=0775

    - name: Symlink web root
      file:
        src: "/vagrant/htdocs"
        dest: "/var/www/htdocs"
        state: "link"

    - name: Copy virtual host setup over
      template: src={{ vhostTemplatePath }} dest=/etc/nginx/sites-available/

    - name: Symlink web root
      file:
        src: "/etc/nginx/sites-available/vhost"
        dest: "/etc/nginx/sites-enabled/vhost"
        state: "link"

    - name: Remove default nginx config (sites-available)
      file: path="/etc/nginx/sites-available/default" state=absent

    - name: Remove default nginx config (sites-enabled)
      file: path="/etc/nginx/sites-enabled/default" state=absent

    - name: Ensure nginx is running
      service: name=nginx state=restarted enabled=yes
